-- Database schema for what-a-fridge (PostgreSQL)

CREATE TABLE IF NOT EXISTS app_user (
    id UUID NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS food (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID,
    open_food_facts_id VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    calories DOUBLE PRECISION NOT NULL,
    protein DOUBLE PRECISION NOT NULL,
    carbohydrates DOUBLE PRECISION NOT NULL,
    fat DOUBLE PRECISION NOT NULL,
    fiber DOUBLE PRECISION,
    sugar DOUBLE PRECISION,
    sodium DOUBLE PRECISION,
    saturated_fat DOUBLE PRECISION,
    is_custom BOOLEAN NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_food_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uk_food_off_id UNIQUE (open_food_facts_id)
);

CREATE TABLE IF NOT EXISTS user_meal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_user_meal_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uk_user_meal_user_name UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS meal_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL,
    user_meal_id BIGINT,
    food_id BIGINT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    consumed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_meal_log_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_meal_log_user_meal FOREIGN KEY (user_meal_id) REFERENCES user_meal(id) ON DELETE SET NULL,
    CONSTRAINT fk_meal_log_food FOREIGN KEY (food_id) REFERENCES food(id)
);

CREATE TABLE IF NOT EXISTS inventory_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL,
    food_id BIGINT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    expiration_date DATE,
    PRIMARY KEY (id),
    CONSTRAINT fk_inventory_item_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_inventory_item_food FOREIGN KEY (food_id) REFERENCES food(id)
);
